src/CupCakesBundle/Entity/Produit.php
<?php

namespace CupCakesBundle\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * produit
 *
 * @ORM\Table(name="produit")
 * @ORM\Entity(repositoryClass="CupCakesBundle\Repository\produitRepository")
 */
class Produit
{


    /**
     * @var int
     *
     * @ORM\Column(name="idProd", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nomProd", type="string", length=500, nullable=true)
     */
    private $nomProd;

    /**
     * @var string
     *
     * @ORM\Column(name="qteStockProd", type="float", nullable=true)
     */
    private $qteStockProd;

    /**
     * @var float
     *
     * @ORM\Column(name="typeProd", type="string",length=255, nullable=true)
     */
    private $typeProd;

    /**
     * @var float
     *
     * @ORM\Column(name="prixProd", type="integer", nullable=true)
     * @Assert\GreaterThan(value="0", message="le prix superieur à zero")
     */
    private $prixProd;

    /**
     * @var float
     *
     * @ORM\Column(name="nv_prix", type="integer", nullable=true)
     * @Assert\GreaterThan(value="0", message="le prix superieur à zero")
     */
    private $nv_prix;

    /**
     * @var string
     *
     * @ORM\Column(name="etatProd", type="string", length=255, nullable=true)
     */
    private $etatProd = "vrai";

    /**
     * @ORM\ManyToOne(targetEntity="CupCakesBundle\Entity\User")
     *
     * @ORM\JoinColumn(name="idUser",referencedColumnName="id")
     */
    private $idUser;

    /**
     * @ORM\ManyToOne(targetEntity="CupCakesBundle\Entity\Categorie")
     *
     * @ORM\JoinColumn(name="idCat",referencedColumnName="idCat")
     */
    private $idCat;

    /**
     * @ORM\Column(name="imageprod",type="string", length=10000, nullable=true)
     *
     * @Assert\NotBlank(message="Please, upload the product brochure as a PDF file.")
     * @Assert\File(mimeTypes={ "image/jpeg","image/jpg","image/png","image/GIF" })
     */
    private $imageProd;


    /**
     * @var integer
     *
     * @ORM\Column(name="QteAcheter", type="integer", nullable=true)
     */
    private $QteAcheter = 0;

    /**
     * @var int
     *
     * @ORM\Column(name="valeur", type="integer")
     */
    private $valeur =0;
    private $tnd;
    private $euro;
    private $usd;

    /**
     * @return mixed
     */
    public function getUsd()
    {
        return $this->usd;
    }

    /**
     * @param mixed $usd
     */
    public function setUsd($usd)
    {
        $this->usd = $usd;
    }


    /**
     * @return mixed
     */
    public function getEuro()
    {
        return $this->euro;
    }

    /**
     * @param mixed $euro
     */
    public function setEuro($euro)
    {
        $this->euro = $euro;
    }


    /**
     * @return mixed
     */
    public function getTnd()
    {
        return $this->tnd;
    }

    /**
     * @param mixed $tnd
     */
    public function setTnd($tnd)
    {
        $this->tnd = $tnd;
    }


    /**
     * @return mixed
     */
    public function getQteAcheter()
    {
        return $this->QteAcheter;
    }

    /**
     * @param mixed $QteAcheter
     */
    public function setQteAcheter($QteAcheter)
    {
        $this->QteAcheter = $QteAcheter;
    }
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nomProd
     *
     * @param string $nomProd
     *
     * @return produit
     */
    public function setNomProd($nomProd)
    {
        $this->nomProd = $nomProd;
    
        return $this;
    }

    /**
     * Get nomProd
     *
     * @return string
     */
    public function getNomProd()
    {
        return $this->nomProd;
    }

    /**
     * Set qteStockProd
     *
     * @param float $qteStockProd
     *
     * @return produit
     */
    public function setQteStockProd($qteStockProd)
    {
        $this->qteStockProd = $qteStockProd;
    
        return $this;
    }

    /**
     * Get qteStockProd
     *
     * @return float
     */
    public function getQteStockProd()
    {
        return $this->qteStockProd;
    }

    /**
     * Set prixProd
     *
     * @param float $prixProd
     *
     * @return produit
     */
    public function setPrixProd($prixProd)
    {
        $this->prixProd = $prixProd;

        return $this;
    }

    /**
     * Get prixProd
     *
     * @return float
     */
    public function getPrixProd()
    {
        return $this->prixProd;
    }

    /**
     * Set etatProd
     *
     * @param string $etatProd
     *
     * @return produit
     */
    public function setEtatProd($etatProd)
    {
        $this->etatProd = $etatProd;
    
        return $this;
    }

    /**
     * Get etatProd
     *
     * @return string
     */
    public function getEtatProd()
    {
        return $this->etatProd;
    }

    /**
     * Set idUser
     *
     * @param \CupCakesBundle\Entity\User $idUser
     *
     * @return produit
     */
    public function setIdUser(\CupCakesBundle\Entity\User $idUser = null)
    {
        $this->idUser = $idUser;
    
        return $this;
    }

    /**
     * Get idUser
     *
     * @return \CupCakesBundle\Entity\User
     */
    public function getIdUser()
    {
        return $this->idUser;
    }

    /**
     * Set idCat
     *
     * @param \CupCakesBundle\Entity\Categorie $idCat
     *
     * @return produit
     */
    public function setIdCat(\CupCakesBundle\Entity\Categorie $idCat = null)
    {
        $this->idCat = $idCat;
    
        return $this;
    }

    /**
     * Get idCat
     *
     * @return \CupCakesBundle\Entity\Categorie
     */
    public function getIdCat()
    {
        return $this->idCat;
    }

    /**
     * Set typeProd
     *
     * @param string $typeProd
     *
     * @return Produit
     */
    public function setTypeProd($typeProd)
    {
        $this->typeProd = $typeProd;
    
        return $this;
    }

    /**
     * Get typeProd
     *
     * @return string
     */
    public function getTypeProd()
    {
        return $this->typeProd;
    }

    /**
     * Set imageProd
     *
     * @param string $imageProd
     *
     * @return Produit
     */
    public function setImageProd($imageProd)
    {
        $this->imageProd = $imageProd;

        return $this;
    }

    /**
     * Get imageProd
     *
     * @return string
     */
    public function getImageProd()
    {
        return $this->imageProd;
    }

    /**
     * @return int
     */
    public function getValeur()
    {
        return $this->valeur;
    }

    /**
     * @param int $valeur
     */
    public function setValeur($valeur)
    {
        $this->valeur = $valeur;
    }

    /**
     * Set nvPrix.
     *
     * @param int|null $nvPrix
     *
     * @return Produit
     */
    public function setNvPrix($nvPrix = null)
    {
        $this->nv_prix = $nvPrix;

        return $this;
    }

    /**
     * Get nvPrix.
     *
     * @return int|null
     */
    public function getNvPrix()
    {
        return $this->nv_prix;
    }
}

src/CupCakesBundle/Controller/CommandeController.php
<?php
/**
 * Created by PhpStorm.
 * User: escobar
 * Date: 09/02/2018
 * Time: 01:31
 */

namespace CupCakesBundle\Controller;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\Histogram;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use CupCakesBundle\Entity\Commande;
use CupCakesBundle\Entity\LineCmd;
use CupCakesBundle\Entity\Produit;
use CupCakesBundle\Entity\User;
use CupCakesBundle\Form\CommandeType;
use CupCakesBundle\Form\LineCmdType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;


class CommandeController extends Controller
{

    public function  AjouterPanierAction($id , SessionInterface $session, Request $request){


        if (!$session->has('panier')) $session->set('panier',array());
        $panier = $session->get('panier');


        if (is_array($panier) && array_key_exists($id, $panier)) {
            if ($request->query->get('qte') != null) $panier[$id] = $request->query->get('qte');
        } else {
            if ($request->query->get('qte') != null)
                $panier[$id] = $request->query->get('qte');
            else
                $panier[$id] = 1;

        }

        $session->set('panier',$panier);


        return $this->redirect($this->generateUrl('AfficherPanier'));

    }

    public function SupprimerPanierAction($id , Request $request){
        $session = $request->getSession();
        $panier = $session->get('panier');

        if (array_key_exists($id, $panier))
        {
            unset($panier[$id]);
            $session->set('panier',$panier);
        }
        return $this->redirect($this->generateUrl('AfficherPanier'));

    }

    public function TrackOrderAction($id)
    {
        $em= $this->getDoctrine()->getManager();
        $commande=$em->getRepository(Commande::class)->find($id);
        if($commande->getEtatLivCmd()== "passée"){
             //si l'etat est en preparation on affiche la page
                //si l'etat est passée on affiche la page
                return $this->render('CupCakesBundle:Client/Commande:TrackOrderetat1.html.twig');
            } else{
                if ($commande->getEtatLivCmd()=="en preparation"){
                    return $this->render('CupCakesBundle:Client/Commande:TrackOrderetat2.html.twig');
            }
            else {
                //si l'etat est livrée on affiche la page
                return $this->render('CupCakesBundle:Client/Commande:TrackOrderEtat3.html.twig');
            }
        }
    }



    public function ValiderPanierAction(Request $request,$total,SessionInterface $session)
    {
        if (!$session->has('panier')) $session->set('panier', array());

        $em = $this->getDoctrine()->getManager();
        $produit = $em->getRepository('CupCakesBundle:Produit')->findArray(array_keys($session->get('panier')));
        $commande = new Commande();
        $em=$this->getDoctrine()->getManager();
        if ($request->isMethod("POST")){
            $commande->setDateCmd(new \DateTime())
                ->setMontantCmd($total)
                ->setIdUser($this->getUser())
            ->setDateLivCmd(new \DateTime($request->get("Dateliv")))
            ->setAdresseLi($request->get("addLiv"));
            $em->persist($commande);
            $em->flush();
           return $this->redirectToRoute("AjouterLine");

        }

        return $this->render('CupCakesBundle:Client/Commande:Commande.html.twig' , array('Commandes'=>$commande,'produits' => $produit,
            'panier'=> $session->get('panier')));

    }

    public function AjouterLineAction(Request $request,SessionInterface $session){

        if (!$session->has('panier')) $session->set('panier', array());
        $em = $this->getDoctrine()->getManager();
        $produit = $em->getRepository('CupCakesBundle:Produit')->findArray(array_keys($session->get('panier')));
        $cmd=$em->getRepository(Commande::class)->findMax();
        $line = new LineCmd();

        if ($request->isMethod("POST")) {

        foreach ($produit as $p){

            $line = new LineCmd();
                $line->setQteAcheter($request->get("Qte"))
                    ->setIdCmd($em->getRepository(Commande::class)->find($cmd->getId()))
                    ->setIdProd($em->getRepository(Produit::class)->find($p));
                $em->persist($line);
                $em->flush();
                $newQte =($em->getRepository(Produit::class)->find($p)->getQteStockProd() - $line->getQteAcheter());
                $QteAcheter=($em->getRepository(Produit::class))->find($p)->getQteAcheter() + $line->getQteAcheter();
                $produp=$em->getRepository(Produit::class)->find($p);
                $produp->setQteStockProd($newQte)
                        ->setQteAcheter($QteAcheter);
                $em->flush();
        }
            $this->get('session')->clear();
            return $this->redirectToRoute("CommandeSuivie");
        }
       //

        return $this->render('CupCakesBundle:Client/Commande:Line.html.twig' , array('lines'=>$line,'produits' => $produit,
            'panier'=> $session->get('panier')));
    }

    public function SupprimerCmdAction($id){
        $em=$this->getDoctrine()->getManager();
        $commande=$em->getRepository(Commande::class)->find($id);
        $commande->setEtatCmd("Faux");
            $em->flush();
            return $this->redirectToRoute('CommandeListePatisserie');

    }

    public function PatisserieListeAction()
    {
        $commande = $this->getDoctrine()->getRepository("CupCakesBundle:Commande")->rechercheId($this->getUser()->getid());
        return $this->render('CupCakesBundle:Patisserie/Commande:ListeCommande.html.twig' , ['Commandes'=>$commande]);

    }

    public function ListeCAction()
    {
        $linecmd= $this->getDoctrine()->getRepository("CupCakesBundle:LineCmd")->findcomm($this->getUser()->getid());
        return $this->render('CupCakesBundle:Client/Commande:MesCommandes.html.twig', ['LineCmd'=>$linecmd]);
    }

    public function SuivantAction(){

        $linecmd= $this->getDoctrine()->getRepository("CupCakesBundle:LineCmd")->findLastcomm($this->getUser()->getid());
        return $this->render('CupCakesBundle:Client/Commande:suivi.html.twig', ['LineCmd'=>$linecmd]);

    }

    public function listeAction(SessionInterface $session)
    {
        if (!$session->has('panier')) $session->set('panier', array());

        $em = $this->getDoctrine()->getManager();
        $produit = $em->getRepository('CupCakesBundle:Produit')->findArray(array_keys($session->get('panier')));

        return $this->render('CupCakesBundle:Client/Commande:ListeCommande.html.twig', ['produits' => $produit,
            'panier' => $session->get('panier')]);


    }
    public function tagsAction()
    {
        $tags = $this->getDoctrine()->getRepository('CupCakesBundle:Tag')->findBy([], ['name' => 'ASC']);

        return $this->render('CupCakesBundle:Patisserie/Produit:CreateProduit.html.twig', ['tags' => $tags]);
    }

    public function UpdateEtatLivraisonAction (Request $request,$id){
        $em=$this->getDoctrine()->getManager();
        $commande=$em->getRepository(Commande::class)->find($id);
        $form=$this->createForm(CommandeType::class,$commande);
        $form->handleRequest($request);
        if ($form->isSubmitted()){

            $em->flush();
            //envoi du mail

            if ($commande->getEtatLivCmd()=="en preparation"){
                $message = \Swift_Message::newInstance()
                    ->setSubject('Votre Commande')
                    ->setFrom(array('cupcakestunisie@gmail.com' => "Cup Cakes"))
                    ->setTo($commande->getIdUser()->getemail())
                    ->setCharset('utf-8')
                    ->setContentType('text/html')
                    ->setBody($this->renderView('CupCakesBundle:Client/Commande:TrackOrderetat2.html.twig'));
            }
            else {
                //si l'etat est livrée on affiche la page
                //return $this->render('CupCakesBundle:Client/Commande:TrackOrderEtat3.html.twig');
            }
            return $this->redirectToRoute('CommandeListePatisserie');
        }

        return $this->render('CupCakesBundle:Patisserie/Commande:Update.html.twig' , ['Commande'=>$commande,'form'=>$form->createView()]);

    }

    public function PDFFactureAction($id){
        $em=$this->getDoctrine()->getManager();
        $linecmd=$em->getRepository(LineCmd::class)->Com($id);
        $cmd=$em->getRepository(Commande::class)->findByid($id);
        $html = $this->renderView('CupCakesBundle:Client/Commande:PDF.html.twig' , ['LineCmd'=>$linecmd ,'Commande'=>$cmd]);

        return new Response(
            $this->get('knp_snappy.pdf')->getOutputFromHtml($html,
                array(
                    'lowquality' => false,
                    'print-media-type' => true,
                    'encoding' => 'utf-8',
                    'page-size' => 'Letter',
                    'outline-depth' => 8,
                )),
            200,
            array(
                'Content-Type'          => 'application/pdf',
                'Content-Disposition'   => 'attachment; filename="file.pdf"'

            ));
    }

    public function RechercheAction(Request $request)
    {
        $search =$request->query->get('username');
        $en = $this->getDoctrine()->getManager();
        $commandes=$en->getRepository("CupCakesBundle:Commande")->findUsername($search);
        return $this->render('CupCakesBundle:Patisserie/Commande:ListeCommande.html.twig',array(
            'Commandes' => $commandes
        ));
    }
    public function RechercheFeedbackAction(Request $request)
    {
        $search =$request->query->get('sujet');
        $en = $this->getDoctrine()->getManager();

src/CupCakesBundle/Resources/views/Client/Commande/MesCommandes.html.twig
{% extends "CupCakesBundle:Client:LayoutC2.html.twig" %}
{% block stylesheet %}
    <style>
        th, td {
            border-bottom: 1px solid #ddd;
        }
    </style>
{% endblock %}
    {% block containt %}
    <!-- Start Main -->
    <main>
        <div class="main-part">
            <!-- Start Breadcrumb Part -->
            <section class="breadcrumb-part" data-stellar-offset-parent="true" data-stellar-background-ratio="0.5" style="background-image: url('{{ asset('ClientTemplate/images/breadbg1.jpg') }}');">
                <div class="container">
                    <div class="breadcrumb-inner">
                        <h2>Mes Commandes</h2>
                        <a href="{{ path('cup_cakes_Eshop') }}">Acceuil</a>
                        <span>Mes Commandes</span>
                    </div>
                </div>
            </section>
            <!-- End Breadcrumb Part -->
            <section class="home-icon shop-cart bg-skeen">
                <div class="icon-default icon-skeen">
                    <img src="{{ asset('ClientTemplate/images/scroll-arrow.png') }}" alt="" />
                </div>
                <div class="container">
                    <div class="track-oder wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                        <div class="track-oder-inner">
                            <div class="clock-track-icon">
                                <img src="{{ asset('ClientTemplate/images/404.png') }}" alt="" />
                            </div>
                            <div class="track-status">
                                <h3><span>Mes Commande:</span></h3>
                                <table>
                                    <thead>
                                    <th>Id Commande</th>
                                    <th>Nom Produit</th>
                                    <th>Prix Unitaire</th>
                                    <th>Quantite</th>
                                    <th>Montant Total Commande</th>
                                    <th>Date Commande</th>

                                    </thead>
                                        {% for line in LineCmd %}
                                    <tbody>
                                            <tr>
                                                <td>
                                                    {{ line.idCmd.id }}
                                                </td>
                                                <td>
                                                    <div class="product-cart-title">
                                                        <span>{{ line.idProd.nomProd }}</span>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="product-cart-title">
                                                        <span class="pu">{{ line.idProd.prixProd }}</span>
                                                    </div>
                                                </td>
                                                <td>
                                                            {{ line.qteAcheter }}
                                                </td>
                                                <td>
                                                    <span class="price">{{ line.idCmd.montantCmd }}</span>
                                                </td>

                                                <td>
                                                    <a href="{{ path('AjouterFeedback',{'id': line.idCmd.id }) }}">Feedback</a>
                                                </td>
                                                <td>
                                                   <a href="{{ path('Pdf',{'id' : line.idCmd.id }) }}"><img src="{{ asset('ClientTemplate/images/pdf.png') }}"></a>
                                                </td>
                                                <td>
                                                    <a href="{{ path('TraceCommande',{'id' : line.idCmd.id }) }}"><img src="{{ asset('ClientTemplate/images/suivre.png') }}"></a>
                                                </td>
                                            </tr>
                                            </tr>

                                        {% endfor %}
                                        </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
    <!-- End Main -->

{% endblock %}

src/CupCakesBundle/Resources/views/Client/Commande/PDF.html.twig
<h3><span>Ma Commande:</span></h3>
{% set frais = 0 %}
{% set tot = 0 %}
<table style="margin-left: 70%;margin-top: auto">
    {% for c in Commande %}
        <tr><td>Adresse de livraison</td></tr>
        <tr><td>{{ c.idUser.prenom }}</td><td>{{ c.idUser.nom }}</td></tr>
        <tr><td>{{ c.adresseLi }}</td></tr>
        <tr><td>Frais de livraison</td><td> 0 tnd</td></tr>
        <tr><td>{{ c.idUser.phoneNumber }}</td></tr>
</table>
<br><br>
<table style="margin-top: 20%;width: 100%;border: 1px solid black;">
    <th style="height: 50px;background-color: #dc5552;
    color: white;">id Commande</th>
    <th style="height: 50px;background-color: #dc5552;
    color: white;">Date de Livraison</th>
    <th style="height: 50px;background-color: #dc5552;
    color: white;">Date de commande</th>
    <tr><td style="padding: 15px;
    text-align: left;">{{ c.id }}</td>
        <td style="padding: 15px;
    text-align: left;"> {{ c.dateLivCmd|date('d M Y') }}</td><td style="padding: 15px;
    text-align: left;">{{ c.dateCmd|date('d M Y') }}</td></tr>
</table>
{% endfor %}

<table style="margin-top: 40%;width: 100%;border: 1px solid black;">
    <thead>
    <th style="height: 50px;background-color: #dc5552;
    color: white;">Poduit</th>
    <th style="height: 50px;background-color: #dc5552;
    color: white;">Prix Unitaire</th>
    <th style="height: 50px;background-color: #dc5552;
    color: white;">Quantite</th>
    <th style="height: 50px;background-color: #dc5552;
    color: white;">TOTAL</th>
    </thead>
    <tbody>
    {% for line in LineCmd %}
        <tr>
        <td style="padding: 15px;
    text-align: left;">
            {{ line.idProd.nomProd }}
        </td>
        <td style="padding: 15px;
    text-align: left;">
            {{ line.idProd.prixProd * 3 }}
        </td>
        <td style="padding: 15px;
    text-align: left;">
            {{ line.qteAcheter }}
        </td>
        <td style="padding: 15px;
    text-align: left;">
            {{ line.idCmd.montantCmd }}
        </td>
    </tr>

    {% endfor %}
    </tbody>
</table>
<table style="margin-bottom: 60%;width: 50%;border: 1px solid black;">
    <tr><td>Moyenne de Paiment</td><td>A la livraison</td></tr>
</table>
<table style="margin-top: 80%;width: 50%;border: 1px solid black;">
    {% for c in Commande %}
    <tr><td>Total Produit</td><td>{{ c.montantCmd }}</td></tr>
    <tr><td>Frais de livraison</td><td>{{ frais }}</td></tr>
        {% set tot = c.montantCmd  + frais %}
    <tr><td>Total</td><td>{{ tot }}</td></tr>
    {% endfor %}
</table>

src/CupCakesBundle/Resources/views/Client/Commande/Suivie.html.twig
{% extends "CupCakesBundle:Client:LayoutC.html.twig" %}
{% block containt %}
    <!-- Start Main -->
    <main>
        <div class="main-part">
            <!-- Start Breadcrumb Part -->
            <section class="breadcrumb-part" data-stellar-offset-parent="true" data-stellar-background-ratio="0.5" style="background-image: url('{{ asset('ClientTemplate/images/breadbg1.jpg') }}');">
                <div class="container">
                    <div class="breadcrumb-inner">
                        <h2>TRACK YOUR ORDER</h2>
                        <a href="#">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </section>
            <!-- End Breadcrumb Part -->
            <section class="home-icon shop-cart bg-skeen">
                <div class="icon-default icon-skeen">
                    <img src="{{ asset('ClientTemplate/images/scroll-arrow.png') }}" alt="" />
                </div>
                <div class="container">
                    <div class="checkout-wrap checkout-wrap-more wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                        <ul class="checkout-bar">
                            <li class="done-proceed">Mon Pannier</li>
                            <li class="done-proceed">Livraison</li>
                            <li class="done-proceed">Commande Complete</li>
                            <li class="active">Ma Commande</li>
                        </ul>
                    </div>
                    <div class="track-oder wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                        <div class="track-oder-inner">
                            <div class="clock-track-icon">
                                <img src="{{ asset('ClientTemplate/images/clock-icon.png') }}" alt="" />
                            </div>
                            <div class="track-status">
                                <h3><span>Mes Commande:</span></h3>

                                        {% for line in LineCmd %}

                                <table>
                                    <tbody>
                                            <tr>{{ line.idCmd.id }}
                                                <td>
                                                    <div class="product-cart-title">
                                                        <span>{{ line.idProd.nomProd }}</span>
                                                    </div>
                                                </td>
                                                <th>Prix</th>
                                                <td>
                                                    <div class="product-cart-title">
                                                        <span class="pu">{{ line.idProd.prixProd }}</span>
                                                    </div>
                                                </td>
                                                <th>Quantité</th>
                                                <td>
                                                            {{ line.qteAcheter }}
                                                </td>
                                                <th>TOTAL</th>
                                                <td>
                                                    <span class="price">{{ line.idCmd.montantCmd }}</span>
                                                </td>
                                                <th>Etat Commande</th>
                                                <td>
                                                    {{ line.idCmd.etatLivCmd }}
                                                </td>
                                                <td>
                                                    <a href="{{ path('AjouterFeedback',{'id':line.idCmd.id}) }}">Feedback</a>
                                                </td>
                                                <td>
                                                    <span><a href="{{ path('Pdf',{'id' : line.idCmd.id }) }}">Pdf</a></span>
                                                </td>
                                            </tr>

                                        {% endfor %}
                                        </tbody>
                                    </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
    <!-- End Main -->

{% endblock %}

src/CupCakesBundle/Resources/views/Client/Commande/TrackOrderEtat2.html.twig
{% extends "CupCakesBundle:Client:LayoutC2.html.twig" %}
{% block containt %}
    <!-- Start Main -->
    <main>
        <div class="main-part">
            <!-- Start Breadcrumb Part -->
            <section class="breadcrumb-part" data-stellar-offset-parent="true" data-stellar-background-ratio="0.5" style="background-image: url('./images/breadbg1.jpg');">
                <div class="container">
                    <div class="breadcrumb-inner">
                        <h2>TRACK YOUR ORDER</h2>
                        <a href="#">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </section>
            <!-- End Breadcrumb Part -->
            <section class="home-icon shop-cart bg-skeen">
                <div class="icon-default icon-skeen">
                    <img src="{{ asset('ClientTemplate/images/scroll-arrow.png') }}" alt="" />
                </div>
                <div class="container">
                    <div class="checkout-wrap checkout-wrap-more wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                        <ul class="checkout-bar">
                            <li class="done-proceed">passée</li>
                            <li class="active">en preparation</li>
                            <li>Livrée</li>
                        </ul>
                    </div>
                    <div class="track-oder wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                        <div class="track-oder-inner">
                            <div class="clock-track-icon">
                                <img src="{{ asset('ClientTemplate/images/icon12.png') }}" alt="" />
                            </div>
                            <div class="track-status">
                                <h3><span>Status:</span> <br /> Cuisson en cours</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
    <!-- End Main -->
{% endblock %}